# Generated by Django 4.2 on 2023-04-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Megnevezes', models.CharField(max_length=255)),
                ('Ar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Idopont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('idopont', models.CharField(max_length=16, unique=True)),
                ('tev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tev_id', to='API.tev')),
            ],
        ),
    ]
